/*
 * Rating Service
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"database/sql"
	"log"
	"net/http"

	"github.com/nfk93/rating-service/db"
	"github.com/nfk93/rating-service/generated/api"
	"github.com/nfk93/rating-service/generated/database"
	"github.com/nfk93/rating-service/internal/endpoints"
	"github.com/nfk93/rating-service/internal/user"

	_ "github.com/go-sql-driver/mysql"
)

func main() {
	log.Printf("Server started")

	sqldb, err := sql.Open("mysql", "user:password@/dbname")
	if err != nil {
		panic("error creating db")
	}
	queries := database.New(sqldb)
	repo := db.NewRepo(queries)

	userService := user.NewUserService(repo)

	DefaultApiService := endpoints.NewApiService(userService)
	DefaultApiController := api.NewDefaultApiController(DefaultApiService)

	router := api.NewRouter(DefaultApiController)
	log.Fatal(http.ListenAndServe(":8080", router))
}
