/*
 * Rating Service
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package endpoints

import (
	"context"
	"errors"
	"net/http"

	"github.com/nfk93/rating-service/generated/api"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() api.DefaultApiServicer {
	return &DefaultApiService{}
}

// UsersGet -
func (s *DefaultApiService) UsersGet(ctx context.Context) (api.ImplResponse, error) {
	// TODO - update UsersGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []User{}) or use other options such as http.Ok ...
	//return Response(200, []User{}), nil

	return api.Response(http.StatusNotImplemented, nil), errors.New("UsersGet method not implemented")
}

// UsersPost -
func (s *DefaultApiService) UsersPost(ctx context.Context, user api.User) (api.ImplResponse, error) {
	// TODO - update UsersPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, string{}) or use other options such as http.Ok ...
	//return Response(201, string{}), nil

	return api.Response(http.StatusNotImplemented, nil), errors.New("UsersPost method not implemented")
}
