openapi: 3.0.0
info:
  title: Rating Service
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.0

# servers:
#   - url: http://api.example.com/v1
#     description: Optional server description, e.g. Main (production) server
#   - url: http://staging-api.example.com
#     description: Optional server description, e.g. Internal staging server for testing

paths:
  /:
    get:
      description: Hello world
      responses:
        200:
          description: Hello world
          content:
            application/json:
              schema:
                type: string
                
  /users:
    get:
      description: Optional extended description in CommonMark or HTML.
      responses:
        200:
          description: A JSON array of users
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/User'
                  
  /users/{username}:
    post:
      description: Create a new user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        201:
          description: User successfully created
          content:
            application/json:
              schema:
                description: The user's ID
                type: string

# Basic authentication
security:
  - BasicAuth: []

components:
  # Basic authentication
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          description: User id
          type: string
        name:
          description: User name
          type: string

  requestBodies:
    PostUserRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'

  